Repository yasminehilout/Big-Eaters-soen341project2023, pull requests merged in 2023-04, with the labels that each got.

#79 CircleCI project setup
  .circleci/config.yml
  src/tests/App.test.js
Labels: enhancement

#57 Created employer edit profile
  src/components/signin.js
  src/components/student-profile.js
  src/config/firebase.js
Labels: User Story

#88 Additional employer fields added + modal size adjustment for more fields
  src/components/css/student-profile.css
  src/components/employerProfile.js
  src/components/signin.js
Labels: enhancement, User Story

#94 GetProfile functions to get the profiles and display it in the inputs
  src/components/employerProfile.js
  src/components/studentProfile.js
Labels: User Story

#80 Adding Component Tests and Code Coverage
  .circleci/config.yml
  .gitignore
  codecov.yml
  cypress/component/auth.cy.js
  cypress/screenshots/specs.cy.js/JobBrowsing -- blocks protected routes (failed).png
  cypress/screenshots/specs.cy.js/JobBrowsing -- has a title (failed).png
  cypress/screenshots/specs.cy.js/JobBrowsing -- signs up a new user (failed).png
  firebase.json
  package-lock.json
  package.json
  src/App.js
  src/app/store.js
  src/components/action.js
  src/components/auth.js
  src/components/browsing.js
  src/components/css/browsing.css
  src/components/employerProfile.js
  src/components/navbar.js
  src/components/notificationsButton.js
  src/components/reducer.js
  src/components/signin.js
  src/components/signout.js
  src/components/studentProfile.js
  src/components/uploadFile.js
  src/config/firebase.js
  src/coverage/lcov.info
  src/features/counter/Counter.js
  src/features/counter/Counter.module.css
  src/features/counter/counterAPI.js
  src/features/counter/counterSlice.js
  src/features/counter/counterSlice.spec.js
  src/features/counter/profileSlice.js
  src/features/counter/userSlice.js
  src/index.js
  src/reportWebVitals.js
  src/tests/App.test.js
  src/tests/Browsing.test.js
  src/tests/EmployerProfile.test.js
  src/tests/Index.test.js
  src/tests/LoginMenu.test.js
  src/tests/LogoutMenu.test.js
  src/tests/Navbar.test.js
  src/tests/NotificationsButton.test.js
  src/tests/UploadFile.test.js
  src/tests/studentProfile.test.js
Labels: enhancement

#95 added website logo
  src/components/css/logo.css
  src/components/images/logo.svg
  src/components/navbar.js
Labels: enhancement
