Repository yasminehilout/Big-Eaters-soen341project2023, pull requests merged in 2023-03, with the labels that each got.

#45 Created an Edit Profile Modal using student-profile.js and created an Edit profile button to trigger Modal
  package-lock.json
  package.json
  src/App.js
  src/components/css/student-profile.css
  src/components/navbar.js
  src/components/student-profile.js
Labels: User Story

#56 User edit profile menu modal/UI Color Update
  src/components/css/browsing.css
  src/components/css/student-profile.css
  src/components/navbar.js
  src/components/profile.js
  src/components/student-profile.js
Labels: enhancement

#61 Fixed issue with DB not adding new students.
  src/components/browsing.js
  src/components/signin.js
Labels: bug

#46 Continuous Integration (Automated Testing)
  cypress.config.js
  cypress/component/auth.cy.js
  cypress/e2e/specs.cy.js
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/screenshots/specs.cy.js/JobBrowsing -- blocks protected routes (failed).png
  cypress/screenshots/specs.cy.js/JobBrowsing -- has a title (failed).png
  cypress/screenshots/specs.cy.js/JobBrowsing -- signs up a new user (failed).png
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  cypress/support/googleAuth.js
  cypress/support/index.js
  cypress/videos/specs.cy.js.mp4
  package-lock.json
  package.json
  src/config/firebase.js
Labels: enhancement
